### ISSUE TITLE
Doesn't highlight a .jq file

### ISSUE THREAD

**Issue by Integralist** [bfrg/vim-jq#6]
I'm using Neovim (not that it should matter I guess) and I'm finding that opening a .jq file doesn't get any syntax highlighting.

Even if I `:setf jq` or maybe the filetype is wrong.

Any ideas on how to debug this?

Thanks.

**Comment by bfrg** [comment]
1. What is the output of `:verbose set ft?` and `:set syntax?` after you opened a `.jq` file?
2. Can you also check the output of `:scriptnames` after opening a `.jq` file? For example, when I run the command the output will list the following two script files (amongst others):
```
...
145: ~/.vim/pack/WIP/start/vim-jq/ftplugin/jq.vim
146: ~/.vim/pack/WIP/start/vim-jq/syntax/jq.vim
...
```
3. Into which directory did you download the plugin? I'm not familiar with Neovim's directory structure. Can you check that the plugin directory is listed in `runtimepath`? You can pretty print `runtimepath` with something like:
```vim
:echo substitute(&rtp, ',', "\n", 'g')
```
